web_app/routes.py
from flask import render_template, Blueprint, redirect, url_for, request, flash, jsonify

from web_app.models import *
from werkzeug.security import check_password_hash
from flask_login import login_user, logout_user, current_user, login_required
import datetime

routes = Blueprint('routes', __name__)

@routes.route('/',  methods=['POST', 'GET'])
def login():
    if request.method == 'POST':
        #check if the login is already used
        user = None
        if request.form.get('login') and request.form.get('password'):
            if User.query.filter_by(login=request.form.get('login')).first():
                user = User.query.filter_by(login=request.form.get('login')).first()
                if check_password_hash(user.password, request.form.get('password')):
                    #login
                    login_user(user)
                    return redirect(url_for('routes.main'))
        flash('Špatně zadané údaje')
        return render_template('login.html')        
    else:
        if current_user.is_authenticated:
            return redirect(url_for('routes.main'))
        return render_template('login.html')

@routes.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('routes.login'))

@routes.route('/main', methods=['GET'])
def main():
    return render_template('main.html')




@routes.route('/zadat_uklizeci', methods=['GET', 'POST'])
def zadat_uklizeci():
    if request.method == 'POST':
        if request.form.get('login') and request.form.get('password'):
            if User.query.filter_by(login = request.form.get('login')).first():
                flash("Uživatel s tímto loginem už existuje.")
            else:
                d = User(
                    login = request.form.get('login'),
                    unhashed_password = request.form.get('password'),
                    name = request.form.get('name') if request.form.get('name') else '',
                    surname = request.form.get('surname') if request.form.get('surname') else '',
                    isAdmin = True if request.form.get('admin') else False,
                )
                db.session.add(d)
                db.session.commit()
                flash("Úspěšně vytvořeno.")
                return redirect(url_for('routes.zadat_uklizeci'))
        else:
            flash("Musíte zadat login a heslo.")
        
        return redirect(url_for('routes.zadat_uklizeci'))
    else:
        return render_template('zadat_uklizeci.html')

@routes.route('/uklizeci', methods=['GET'])
def uklizeci():
    context = {
        "users" : User.query.all()
    }
    return render_template('uklizeci.html', **context)




@routes.route('/zadat_zavadu', methods=['GET', 'POST'])
def zadat_zavadu():
    rooms = Room.query.all()
    numbers = []  
    for r in rooms:
       numbers.append(r.number)
    context = {
        "rooms": numbers
    }
    if request.method == 'POST':
        if request.form.get('number') and request.form.get('description'):
            if not Room.query.filter_by(number = request.form.get('number')).first():
                flash("Pokoj s tímto číslem neexistuje")
            else:
                d = Fault(
                    room = Room.query.filter_by(number = request.form.get('number')).first(),
                    description = request.form.get('description'),
                    date = datetime.datetime.strptime(request.form.get('date'), "%Y-%m-%d") if request.form.get('date') else datetime.datetime.now() ,
                    completed = None,
                )
                db.session.add(d)
                db.session.commit()
                flash("Úspěšně vytvořeno.")
                return redirect(url_for('routes.zadat_zavadu'))
        else:
            flash("Musíte zadat číslo pokoje a popis závady.")
        
        return redirect(url_for('routes.zadat_zavadu'))
    else:
        return render_template('zadat_zavadu.html',**context)

@routes.route('/zavady', methods=['GET'])
def zavady():
    context = {
        "zavady": Fault.query.order_by(Fault.id.desc()).all()
    }
    return render_template('zavady.html', **context)




@routes.route('/nalezy', methods=['GET'])
def nalezy():
    context = {
        "nalezy": Discovery.query.order_by(Discovery.id.desc()).all()
    }
    return render_template('nalezy.html', **context)

@routes.route('/zadat_nalez', methods=['POST', 'GET'])
def zadat_nalez():
    rooms = Room.query.all()
    numbers = []  
    for r in rooms:
       numbers.append(r.number)
    context = {
        "rooms": numbers
    }
    if request.method == 'POST':
        if request.form.get('number') and request.form.get('description'):
            if not Room.query.filter_by(number = request.form.get('number')).first():
                flash("Pokoj s tímto číslem neexistuje")
            else:
                d = Discovery(
                    room = Room.query.filter_by(number = request.form.get('number')).first(),
                    description = request.form.get('description'),
                    date = datetime.datetime.strptime(request.form.get('date'), "%Y-%m-%d") if request.form.get('date') else datetime.datetime.now() ,
                )
                db.session.add(d)
                db.session.commit()
                flash("Úspěšně vytvořeno.")
                return redirect(url_for('routes.zadat_nalez'))
        else:
            flash("Musíte zadat číslo pokoje a popis nálezu.")
        
        return redirect(url_for('routes.zadat_nalez'))
    else:
        return render_template('zadat_nalez.html',**context)



@routes.route('/zadat_uklid', methods=['GET', 'POST'])
def zadat_uklid():
    
    rooms = Room.query.all()
    numbers = []  
    for r in rooms:
       numbers.append(r.number)
    context = {
        "rooms": numbers
    }
    if request.method == 'POST':
        if request.form.get('number') and request.form.get('type') and request.form.get('date'):
            if not Room.query.filter_by(number = request.form.get('number')).first():
                flash("Pokoj s tímto číslem neexistuje")
            else:
                d = Cleanup(
                    room = Room.query.filter_by(number = request.form.get('number')).first(),
                    c_type = CleanupType(int(request.form.get('type'))),
                    to_be_completed = datetime.datetime.strptime(request.form.get('date'), "%Y-%m-%dT%H:%M") if request.form.get('date') else datetime.datetime.now() ,
                )
                db.session.add(d)
                db.session.commit()
                flash("Úspěšně vytvořeno.")
                return redirect(url_for('routes.zadat_uklid'))
        else:
            flash("Musíte zadat číslo pokoje, datum a typ úklidu.")
        
        return redirect(url_for('routes.zadat_uklid'))
    else:
        return render_template('zadat_uklid.html', **context)

@routes.route('/uklidy', methods=['GET'])
def uklidy():
    context = {
        "uklidy": Cleanup.query.order_by(Cleanup.to_be_completed.asc()).all(),
        "enum" : CleanupType.__members__
    }
    return render_template('uklidy.html', **context)


@routes.route('/user_check', methods=['POST'])
def username_check():
    if request.form.get('login'):
        if User.query.filter_by(login = request.form.get('login')).first():
            resp = jsonify('<span style=color:red;>Login je jiz pouzivan.</span>')
            resp.status_code = 200
            return resp
        else:
            resp = jsonify('<span style=color:green;>Login je k dispozici.</span>')
            resp.status_code = 200
            return resp
    else:
        resp = jsonify('<span style=color:red;>Je nutne zvolit login.</span>')
        resp.status_code = 200
        return resp

@routes.route("/ajax", methods=["POST","GET"])
def ajax():
    if request.form.get('id'):
        user = User.query.filter_by(id = int(request.form.get('id'))).first()
        if request.form.get('login'):  
            user.login = request.form.get('login')
        elif request.form.get('name'):
            user.name = request.form.get('name')
        elif request.form.get('surname'):
            user.surname = request.form.get('surname')
        elif request.form.get('admin'):
            value = (request.form.get('admin') == "true")
            user.isAdmin = value
    db.session.commit()
    resp = jsonify("success")
    resp.status_code = 200
    return resp

web_app/templates/base.html
<!DOCTYPE html>
<html lang="cs">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="shortcut icon" href="{{ url_for('static', filename='css/img/favicon.ico') }}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,200;0,700;0,900;1,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,200;0,400;0,900;1,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,200;0,400;0,500;0,900;1,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet"> 
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <script>
                var messages = {{ messages | safe }};
                for (var i=0; i<messages.length; i++) {
                    alert(messages[i]);
                }
            </script>
        {% endif %}
    {% endwith %}
    {% block head %} {% endblock %}
</head>

<body>
    <div class="menu-mobile">
        <label for="toggle"><img src="{{url_for('static', filename='css/img/menu1.png')}}" alt="menu-bars"  class="menu-bars"></label>
    </div>
    <input type="checkbox" id="toggle" />
    <div class="menu">
        <nav class="main-menu">
            <a href="{{ url_for('routes.main') }}" class="main-icon">Rentel</a>
            <ul>
                <li>
                    <a class="level" href="{{ url_for('routes.uklidy') }}">Úklidy</a>
                    <ul>
                        <li><a href="{{ url_for('routes.zadat_uklid') }}">Zadat úklid</a></li>
                        <li><a href="{{ url_for('routes.uklidy') }}">Seznam úklidů</a></li>
                    </ul>
                </li>
                <li>
                    <a class="level" href="{{ url_for('routes.zadat_zavadu') }}">Závady</a>
                    <ul>
                        <li><a href="{{ url_for('routes.zadat_zavadu') }}">Zadat závadu</a></li>
                        <li><a href="{{ url_for('routes.zavady') }}">Seznam závad</a></li>
                    </ul>
                </li>
                <li>
                    <a class="level" href="{{ url_for('routes.nalezy') }}">Nálezy</a>
                    <ul>
                        <li><a href="{{ url_for('routes.zadat_nalez') }}">Přidat nález</a></li>
                        <li><a href="{{ url_for('routes.nalezy') }}">Seznam nálezů</a></li>


                    </ul>
                </li>
                <li>
                    <a class="level" href="{{ url_for('routes.uklizeci') }}">Správa uživatelů</a>
                    <ul>
                        <li><a href="{{ url_for('routes.zadat_uklizeci') }}">Přidat uživatelů</a></li>
                        <li><a href="{{ url_for('routes.uklizeci') }}">Seznam uživatelů</a></li>
                    </ul>
                </li>
                <li><a href="{{ url_for('routes.logout') }}" class="level">Odhlásit</a></li>
            </ul>
        </nav>
    </div>
    <div class="base-content">
        {% block body %} {% endblock %}
    </div>
</body>

</html>

web_app/templates/login.html
<!DOCTYPE html>
<html lang="cs">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/login_style.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='css/img/favicon.ico') }}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,200;0,700;0,900;1,700&display=swap" rel="stylesheet">
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <script>
                var messages = {{ messages | safe }};
                for (var i=0; i<messages.length; i++) {
                    alert(messages[i]);
                }
            </script>
        {% endif %}
    {% endwith %}
</head>

<body>
    <div class="content">
        <div class="login_form">
            <h1>Systém pro úklid</h1>
            <h1>Rentel</h1>
        </div>
        <form method="POST" action="{{ url_for('routes.login') }}">
            <h2>Login:</h2>
            <input type="text" name="login" id="login">
            <h2>Heslo:</h2>
            <input type="password" name="password" id="password">
            <input type="submit" value="Přihlásit se">
        </form>
    </div>
</body>


</html>

web_app/templates/main.html
<!DOCTYPE html>
<html lang="cs">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main_style.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='css/img/favicon.ico') }}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,200;0,700;0,900;1,700&display=swap" rel="stylesheet">
</head>

<body>
    <div class="content">
        <a href="{{ url_for('routes.zadat_uklid') }}">
            <div class="card"> Zadat úklid</div>
        </a>
        <a href="{{ url_for('routes.zadat_zavadu') }}">
            <div class="card"> Zadat závadu</div>
        </a>
        <a href="{{ url_for('routes.zadat_nalez') }}">
            <div class="card"> Zadat nález</div>
        </a>
        <a href="{{ url_for('routes.uklidy') }}">
            <div class="card"> Seznam úklidů</div>
        </a>
        <a href="{{ url_for('routes.zavady') }}">
            <div class="card"> Seznam závad</div>
        </a>
        <a href="{{ url_for('routes.nalezy') }}">
            <div class="card"> Seznam nálezů</div>
        </a>
        <a href="{{ url_for('routes.zadat_uklizeci') }}">
            <div class="card">Přidat uživatele</div>
        </a>
        <a href="{{ url_for('routes.uklizeci') }}">
            <div class="card">Správa uživatelů</div>
        </a>
        <a href="{{ url_for('routes.logout') }}">
            <div class="card">Odhlásit se</div>
        </a>
    </div>
</body>


</html>

web_app/templates/nalezy.html
{% extends 'base.html' %} {% block head %} {% endblock %} {% block body %}
<div class="content">
    <h3>Seznam nálezů</h3>
    <table>
        <tr>
            <th>Pokoj</th>
            <th>Datum</th>
            <th>Popis</th>
        </tr>
        {% for n in nalezy %}
            <tr>
                <td>{{ n.room.number }}</td>
                <td>{{ n.date.strftime('%d-%m-%Y') }}</td>
                <td>{{ n.description }}</td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

web_app/templates/pobyty.html
{% extends 'base.html' %} {% block head %} {% endblock %} {% block body %}
<div class="content">
    <h3>Seznam pobytů</h3>
    <table>
        <tr>
            <th>Pokoj</th>
            <th>Počet osob</th>
            <th>Check-in</th>
            <th>Check-out</th>
        </tr>
        <tr>
            <td>5</td>
            <td>5</td>
            <td>25.1.2021</td>
            <td>27.1.2021</td>
        </tr>
        <tr>
            <td>5</td>
            <td>5</td>
            <td>17.1.2021</td>
            <td>29.1.2021</td>
        </tr>
        <tr>
            <td>5</td>
            <td>5</td>
            <td>25.1.2021</td>
            <td>27.1.2021</td>
        </tr>
                <tr>
            <td>5</td>
            <td>5</td>
            <td>25.1.2021</td>
            <td>27.1.2021</td>
        </tr>

    </table>
</div>
{% endblock %}

web_app/templates/uklidy.html
{% extends 'base.html' %} {% block head %} {% endblock %} {% block body %}

<div class="content">
    <h3>Seznam úklidů</h3>
    <table>
        <tr id="header">
            <th>Pokoj</th>
            <th>Datum</th>
            <th>Čas</th>
            <th>Typ</th>
            <th>Splněno</th>
        </tr>
        {% for u in uklidy %}
            <tr>
                <td>{{ u.room.number }}</td>
                <td>{{ u.to_be_completed.strftime('%d-%m-%Y') }} </td>
                <td>{{ u.to_be_completed.strftime('%H:%M') }} </td>
                <td>{{ u.c_type.name }}</td>
                <td><input type="checkbox" {% if u.completed %}checked{% endif %} disabled></td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

web_app/templates/zadat_nalez.html
{% extends 'base.html' %} {% block head %} {% endblock %} {% block body %}
<div class="content">
    <h1>Zadat nález</h1>
    <form method="POST" action="{{ url_for('routes.zadat_nalez') }}">
        <div class="form-content">
            <div class="grid">
                <h2>Číslo pokoje:</h2>
            </div>
            <div class="grid" >
                <input type="number" name="number" id="pokoj-check"  onkeyup="kontrola_pokoje(this.value)">
                <span id="error" style="color:red;font-size:15px;display:none">Tento pokoj neexistuje</span>
            </div>
            <script>
                function kontrola_pokoje(str) {
                    var ajax = new XMLHttpRequest();
                    ajax.open("GET", "https://data.heroku.com/dataclips/pdbhlscepyvsjyxaprgjocvqktac.csv", true);
                    ajax.send();
                    
                    ajax.onreadystatechange = function() {
                        if (this.readyState == 4 && this.status == 200) {
                            console.log("Data from heroku:");
                            console.log(this.responseText);
                            
                            var roomss = this.responseText;
                            var rooms = roomss.split('\n');
                            var nalezen = 0;
                            for (i = 0; i < rooms.length; i++) {
                                if(str == rooms[i]){
                                    nalezen = 1;
                                }
                            } 
                            if (nalezen == 1) {
                                document.getElementById("pokoj-check").style.boxShadow = "0 0px 0px 0 rgb( 0,255, 0), 0 0px 6px 0 rgb( 0,255, 0)";
                                document.getElementById("error").style.display="none";
                                console.log("found;");
                            }else if(nalezen == 0){
                                document.getElementById("pokoj-check").style.boxShadow = "0 0px 0px 0 rgb(255, 0, 0), 0 0px 6px 0 rgb(255, 0, 0)";
                                document.getElementById("error").style.display="block";
                                console.log("not found;");
                                } 
                            if(str == ""){
                                document.getElementById("pokoj-check").style.boxShadow = "0 0px 0px 0 rgb( 0,0, 0), 0 0px 0px 0 rgb( 0,0, 0)";
                                document.getElementById("error").style.display="none";
                                console.log("empty;");
                            }
                        }
                        
                    };
                    
                    /*
                    var ajax2 = new XMLHttpRequest();
                    ajax2.open("GET", "ec2-46-137-177-160.eu-west-1.compute.amazonaws.com/d9m4ru2ru00bk5", true,"hvahcpphomtrwf","65e5d855c2ce0cec911a4ad1234bcbde34aaeca3e5245d54ffcaa0b9bee63679");
                    ajax2.send();
                    
                    ajax2.onreadystatechange = function() {
                        if (this.readyState == 4 && this.status == 200) {
                            console.log(this.responseText);
                            var roomss = this.responseText;
                            var rooms = roomss.split('\n');
                            var nalezen = 0;
                            for (i = 0; i < rooms.length; i++) {
                                if(str == rooms[i]){
                                    nalezen = 1;
                                }
                            } 
                            if (nalezen == 1) {
                                document.getElementById("pokoj-check").style.boxShadow = "0 0px 0px 0 rgb( 0,255, 0), 0 0px 6px 0 rgb( 0,255, 0)";
                                document.getElementById("error").style.display="none";
                            }else if(nalezen == 0){
                                document.getElementById("pokoj-check").style.boxShadow = "0 0px 0px 0 rgb(255, 0, 0), 0 0px 6px 0 rgb(255, 0, 0)";
                                document.getElementById("error").style.display="block";
                                } 
                            if(str == ""){
                                document.getElementById("pokoj-check").style.boxShadow = "0 0px 0px 0 rgb( 0,0, 0), 0 0px 0px 0 rgb( 0,0, 0)";
                                document.getElementById("error").style.display="none";
                            }
                        }
                    };
                    */
                    }
                    
                   /* const sql = postgres('postgres://hvahcpphomtrwf:65e5d855c2ce0cec911a4ad1234bcbde34aaeca3e5245d54ffcaa0b9bee63679@ec2-46-137-177-160.eu-west-1.compute.amazonaws.com:5432/d9m4ru2ru00bk5', {
                    port            : 5432,       // Postgres server port
                    database        : 'd9m4ru2ru00bk5',         // Name of database to connect to
                    username        : 'hvahcpphomtrwf',         // Username of database user
                    password        : '65e5d855c2ce0cec911a4ad1234bcbde34aaeca3e5245d54ffcaa0b9bee63679',         // Password of database user
                    transform       : {
                        column            : fn, // Transforms incoming column names
                        value             : fn, // Transforms incoming row values
                        row               : fn  // Transforms entire rows
                    },
                    connection      : {
                        application_name  : 'postgres.js', // Default application_name
                    }
                    })*/
                        
                
            </script>
            <div class="grid">
                <h2>Datum:</h2>
            </div>
            <div class="grid"> <input type="date" name="date" id="date"></div>
            <div class="grid">
                <h2>Popis nálezu:</h2>
            </div>
            <div class="grid"><input type="text" name="description" id="description"></div>
            <div class="grid"><a href="{{url_for('routes.nalezy')}}">Všechny nálezy</a></div>
            <div class="grid"><input type="submit" value="Zadat"></div>
        </div>
    </form>
</div>
{% endblock %}

web_app/templates/zadat_uklid.html
{% extends 'base.html' %}  {% block head %} {% endblock %} {% block body %}
<div class="content">
    <h1>Zadat úklid</h1>
    <form method="POST" action="{{ url_for('routes.zadat_uklid') }}">
        <div class="form-content">
            <div class="grid">
                <h2>Číslo pokoje:</h2>
            </div>
            
            <div class="grid" >
                <input type="number" name="number" id="searchField" >
                <script src="{{ url_for('static', filename='js/searchRooms.js') }}"></script>
                <span id="error" style="color:red;font-size:15px;display:none">Tento pokoj neexistuje</span>
            </div>
          
            <div class="grid">
                <h2>Datum a čas:</h2>
                <p>pro dokončení úklidu</p>
            </div>
            <div class="grid"> <input type="datetime-local" name="date" id="date"></div>
            <div class="grid">
                <h2>Typ úklidu:</h2>
            </div>
            <div class="grid">
                <select name="type" id="type">
                    <option value="0" selected>Standartní</option>
                    <option value="1">Předúklid</option>
                    <option value="2">Minibar</option>
                    <option value="3">Kompletní</option>
                </select>
            </div>
            <div class="grid"><a href="{{url_for('routes.uklidy')}}">Seznam všech úklidů</a></div>
            <div class="grid"><input type="submit" value="Zadat"></div>
        </div>
    </form>
</div>
{% endblock %}

web_app/templates/zadat_uklizeci.html
{% extends 'base.html' %} {% block head %} {% endblock %} {% block body %}
<div class="content">
    <h1>Přidat uživatele</h1>
    <form method="POST" action="{{ url_for('routes.zadat_uklizeci') }}">
        <div class="form-content">
            <div class="grid">
                <h2>Jméno:</h2>
            </div>
            <div class="grid">
                <input type="text" id="name" name="name">
            </div>
            <div class="grid">
                <h2>Příjmení:</h2>
            </div>
            <div class="grid">
                <input type="text" name="surname" id="surname">
            </div>
            <div class="grid">
                <h2>Login:</h2>
            </div>
            <div class="grid">
                <input type="text" name="login" id="login">
            </div>
            <div id="msg">

            </div>
            <div class="grid">
                <h2>Heslo:</h2>
            </div>
            <div class="grid">
                <input type="password" name="password" id="password">
            </div>
            <div class="grid">
                <h2>Admin(Ano/Ne)</h2>
            </div>
            <div class="grid">
                <label class="checkmark">
                    <input type="checkbox" name="admin" is="admin">
                    <span class="checkbox-custom rectangular"></span>
                </label>
            </div>
            <div class="grid">
                <a href="{{url_for('routes.uklizeci')}}">Seznam všech uživatelů</a>
            </div>
            <div class="grid">
                <input type="submit" value="Zadat">
            </div>
        </div>
    </form>
</div>
</div>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script>
$(document).ready(function() {
    $("#login").on('input', function(e) {
        $('#msg').hide();
        if ($('#login').val() == null || $('#login').val() == "") {
            $('#msg').show();
            $("#msg").html("Je nutne zadat login.").css("color", "red");
        } else {
            $.ajax({
                type: "POST",
                url: "/user_check",
                data: $('#login').serialize(),
                dataType: "html",
                cache: false,
                success: function(msg) {
                    $('#msg').show();
                    $('#loading').hide();
                    $("#msg").html(msg);
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    $('#msg').show();
                    $('#loading').hide();
                    $("#msg").html(textStatus + " " + errorThrown);
                }
            });
        }
   });
});
</script>
{% endblock %}

web_app/templates/zadat_zavadu.html
{% extends 'base.html' %} {% block head %} {% endblock %} {% block body %}
<div class="content">
    <h1>Zadat závadu</h1>
    <form method="POST" action="{{ url_for('routes.zadat_zavadu') }}">
        <div class="form-content">
            <div class="grid">
                <h2>Pokoj:</h2>
            </div>
            <div class="grid" >
                <input type="number" name="number" id="pokoj-check"  onkeyup="kontrola_pokoje(this.value)">
                <span id="error" style="color:red;font-size:15px;display:none">Tento pokoj neexistuje</span>
            </div>
            <script>
                function kontrola_pokoje(str) {
                    var rooms = {{rooms | safe}};
                    var nalezen = 0;
                    for (i = 0; i < rooms.length; i++) {
                        if(str == rooms[i]){
                            nalezen = 1;
                        }
                    } 
                    if (nalezen == 1) {
                        document.getElementById("pokoj-check").style.boxShadow = "0 0px 0px 0 rgb( 0,255, 0), 0 0px 6px 0 rgb( 0,255, 0)";
                        document.getElementById("error").style.display="none";
                    }else if(nalezen == 0){
                        document.getElementById("pokoj-check").style.boxShadow = "0 0px 0px 0 rgb(255, 0, 0), 0 0px 6px 0 rgb(255, 0, 0)";
                        document.getElementById("error").style.display="block";
                        } 
                    if(str == ""){
                        document.getElementById("pokoj-check").style.boxShadow = "0 0px 0px 0 rgb( 0,0, 0), 0 0px 0px 0 rgb( 0,0, 0)";
                        document.getElementById("error").style.display="none";
                    }
                    }
                
            </script>
            <div class="grid">
                <h2>Datum:</h2>
            </div>
            <div class="grid">
                <input type="date" name="date" id="date">
            </div>
            <div class="grid">
                <h2>Popis závady:</h2>
            </div>
            <div class="grid">
                <input name="description" id="description" type="text">
            </div>
            <div class="grid">
                <a href="{{ url_for('routes.zavady') }}">Seznam všech závad</a>
            </div>
            <div class="grid">
                <input type="submit" value="Zadat">
            </div>
        </div>
    </form>
</div>
{% endblock %}

web_app/templates/zavady.html
{% extends 'base.html' %} {% block head %} {% endblock %} {% block body %}
<div class="content">
    <h3>Seznam závad</h3>
    <table>
        <tr>
            <th>Pokoj</th>
            <th>Datum</th>
            <th>Popis</th>
        </tr>
        {% for zavada in zavady %}
            <tr>
                <td>{{ zavada.room.number }}</td>
                <td>{{ zavada.date.strftime('%d-%m-%Y') }}</td>
                <td>{{ zavada.description }}</td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}